spring.application.name=MCP
server.port=8080

# Logging
logging.level.org.springframework=INFO

#  Salesforce Credentials 
CLIENT_ID=dummy
CLIENT_SECRET=dummy
SF_USERNAME=dummy
PASSWORD_AND_TOKEN=dummy